on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Auto-release d'un tag

jobs:
  build:
    name: auto-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fetch tags properly
      - name: Create release
        run: gh release create ${{ github.ref_name }} --notes-from-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
